# applied svm and naive bayes

In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [18]:
df = pd.read_csv("1.csv", encoding='latin-1')

In [19]:
df.head()

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0

In [20]:
df.shape

(5172, 3002)

In [21]:
df

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,Email 5168,2,2,2,3,0,0,32,0,0,...,0,0,0,0,0,0,0,0,0,0
5168,Email 5169,35,27,11,2,6,5,151,4,3,...,0,0,0,0,0,0,0,1,0,0
5169,Email 5170,0,0,1,1,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,1
5170,Email 5171,2,7,1,0,2,1,28,2,0,...,0,0,0,0,0,0,0,1,0,1
5171,Email 5172,22,24,5,1,6,5,148,8,2,...,0,0,0,0,0,0,0,0,0,0

In [22]:
x=df.iloc[: ,:-1]
y=df.iloc[: ,-1]

In [23]:
x=x.drop('Email No.' ,axis=1)

In [24]:
x.info

<bound method DataFrame.info of       the  to  ect  and  for  of    a  you  hou  in  ...  enhancements
0       0   0    1    0    0   0    2    0    0   0  ...             0  \
1       8  13   24    6    6   2  102    1   27  18  ...             0
2       0   0    1    0    0   0    8    0    0   4  ...             0
3       0   5   22    0    5   1   51    2   10   1  ...             0
4       7   6   17    1    5   2   57    0    9   3  ...             0
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...           ...
5167    2   2    2    3    0   0   32    0    0   5  ...             0
5168   35  27   11    2    6   5  151    4    3  23  ...             0
5169    0   0    1    1    0   0   11    0    0   1  ...             0
5170    2   7    1    0    2   1   28    2    0   8  ...             0
5171   22  24    5    1    6   5  148    8    2  23  ...             0

      connevey  jay  valued  lay  infrastructure  military  allowing  ff  dry
0            0    0       0    0               0         0         0   0    0
1            0    0       0    0               0         0         0   1    0
2            0    0       0    0               0         0         0   0    0
3            0    0       0    0               0         0         0   0    0
4            0    0       0    0               0         0         0   1    0
...        ...  ...     ...  ...             ...       ...       ...  ..  ...
5167         0    0       0    0               0         0         0   0    0
5168         0    0       0    0               0         0         0   1    0
5169         0    0       0    0               0         0         0   0    0
5170         0    0       0    0               0         0         0   1    0
5171         0    0       0    0               0         0         0   0    0

[5172 rows x 3000 columns]>

In [25]:
y

0       0
1       0
2       0
3       0
4       0
       ..
5167    0
5168    0
5169    1
5170    1
5171    0
Name: Prediction, Length: 5172, dtype: int64

In [26]:
from sklearn import preprocessing
scaler=preprocessing.MinMaxScaler()
x=scaler.fit_transform(x)

In [27]:
from sklearn.model_selection import train_test_split
x_train ,x_test ,y_train , y_test =train_test_split(x,y,test_size=0.2)

In [28]:
from sklearn import svm
from sklearn.metrics import accuracy_score

#linear kernel
clf =svm.SVC(kernel='linear' )
clf.fit(x_train , y_train)
y_pred=clf.predict(x_test)


acc=accuracy_score(y_test , y_pred)
print('accuracy_score= ',acc)

accuracy_score=  0.9681159420289855

In [29]:
clf =svm.SVC(kernel='rbf' )
clf.fit(x_train , y_train)
y_pred=clf.predict(x_test)


acc=accuracy_score(y_test , y_pred)
print('accuracy_score= ',acc)

accuracy_score=  0.9536231884057971

In [30]:
clf =svm.SVC(kernel='poly' )
clf.fit(x_train , y_train)
y_pred=clf.predict(x_test)


acc=accuracy_score(y_test , y_pred)
print('accuracy_score= ',acc)

accuracy_score=  0.7603864734299517

In [31]:
clf =svm.SVC(kernel='sigmoid' )
clf.fit(x_train , y_train)
y_pred=clf.predict(x_test)


acc=accuracy_score(y_test , y_pred)
print('accuracy_score= ',acc)

accuracy_score=  0.8599033816425121

In [32]:
from sklearn.naive_bayes import GaussianNB
clf =GaussianNB( )
clf.fit(x_train , y_train)
y_pred=clf.predict(x_test)


acc=accuracy_score(y_test , y_pred)
print('accuracy_score= ',acc)

accuracy_score=  0.9256038647342996